cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_summary, name='cart_summary'),
    path('add/', views.cart_add, name='cart_add'),
    path('delete/', views.cart_delete, name='cart_delete'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls',namespace='store')),
    path('cart/', include('cart.urls',namespace='cart')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views

app_name='store'

urlpatterns = [
    path('', views.product_all, name='product_all'),
    path('<slug:slug>', views.product_detail, name='product_detail'),
    path('shop/<slug:category_slug>/', views.category_list, name='category_list'),
]


cart/models.py
from django.db import models

# Create your models here.

store/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse

# Create your models here.


class ProductManager(models.Manager):
  ''''filtering out the all active products which are not out of stock and returning it in views of all_products'''
  def get_queryset(self):
    return super(ProductManager, self).get_queryset().filter(out_of_stock=False)

class Category(models.Model):
  name = models.CharField(max_length=255,db_index=True)
  slug = models.SlugField(max_length=255,unique=True)

  class Meta:
    verbose_name_plural='categories'

  def get_absolute_url(self):
      return reverse("store:category_list", args={self.slug})
  

  def __str__(self):
    return self.name


class Product(models.Model):
  category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
  created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='product_creator')
  title = models.CharField(max_length=255)
  author = models.CharField(max_length=255, default='Er. Dipesh')
  description = models.TextField(blank=True)
  image = models.ImageField(upload_to='images/', default='images/default.jpg')
  slug = models.SlugField(max_length=255)
  price = models.DecimalField(max_digits=4,decimal_places=2)
  in_stock = models.BooleanField(default=True)
  out_of_stock = models.BooleanField(default=False)
  created = models.DateTimeField(auto_now_add=True)
  updated = models.DateTimeField(auto_now=True)
  objects = models.Manager()
  products = ProductManager()

  class Meta: 
    verbose_name_plural = 'Products'
    ordering = ('-created',)

  def get_absolute_url(self):
    return reverse('store:product_detail', args=[self.slug])

  def __str__(self):
    return self.title




cart/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.http import JsonResponse

from store.models import Product
from .cart import Cart

# Create your views here.


def cart_summary(request):
    cart = Cart(request)
    return render(request, 'store/cart/summary.html', {'cart': cart})


def cart_add(request):
    cart = Cart(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        product = get_object_or_404(Product, id=product_id)
        cart.add(product=product, qty=product_qty)

        cartqty = cart.__len__()
        response = JsonResponse({'qty': cartqty})

        return response


def cart_delete(request):
    cart = Cart(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        cart.delete(product=product_id)

store/views.py
from django.shortcuts import get_object_or_404, render

from .models import Category, Product

# Create your views here.



def product_all(request):
  products = Product.products.all()
  return render(request,'store/home.html',{'products':products})

def product_detail(request,slug):
  product = get_object_or_404(Product, slug=slug, in_stock=True)
  return render(request, 'store/products/single.html', {'product':product})

def category_list(request, category_slug):
  category= get_object_or_404(Category, slug=category_slug)
  products= Product.objects.filter(category=category)
  return render(request, 'store/products/category.html', {'category': category, 'products': products})

templates/store/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} Divine Store {% endblock %}</title>
    <link rel="stylesheet" href=" {% static 'css/main.css' %} " />

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" />
    <script src="https://code.jquery.com/jquery-3.6.3.min.js"
      integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
      integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
      integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous">
    </script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" rel="stylesheet">

    <style>
      body{
        background-color:rgb(4, 0, 24) ;
        color: rgb(138, 138, 138);
      }
      .nav-scroller {
        background-color: rgb(255, 214, 151);
      }

      .nav-scroller a{
        text-decoration: none;
        font-size: large;
        color:rgb(3, 0, 34);
        font-weight: 600;
      }

      .tabb-1{
        background-color: rgb(28, 0, 20);
      }
      .tabb-2{
        background-color: rgb(35, 0, 0);
      }

      .sidexx:hover{
        box-shadow: 0 2px 5px 1px rgb(255, 213, 0);

      }

      .hawa{
        background-color: rgb(1, 0, 15);
      }
      .hawa:hover{
        box-shadow: 0 2px 3px 2px grey;
      }

      .wild-wise{
        background-color: rgb(27, 27, 27) !important;
      }

      .bullet-rem{
        text-align: left;
      }
      a{
        text-decoration: none;
        color: rgb(174, 174, 174);
      }
    </style>


  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-md navbar-light bg-white border-bottom">
        <div class="container-fluid">
          <a class="navbar-brand" href="/">DivineStore</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar"></button>

          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
              {% comment %} <li class="nav-item active"><a class="nav-link" aria-current="page" href="/">Home</a></li>
              <li class="nav-item"><a class="nav-link" href="#">Link</a></li> {% endcomment %}
              <li class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
                  aria-expanded="false">
                  Library
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="{% url "store:product_all" %}">All</a></li>

                  {% for c in categories %}

                  <li>
                    <a class="dropdown-item text-dark text-decoration-none"
                      href="{{ c.get_absolute_url }}">{{ c.name|title }} </a>
                  </li>

                  {% endfor %}

                </ul>
              </li>
            </ul>

            {% comment %} <form class="d-flex"><input class="form-control me-2" type="search" placeholder="Search"
                aria-label="Search" />
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form> {% endcomment %}
            <a type="button" class="btn btn-primary" href="{% url 'cart:cart_summary' %}" role="button">
              

              {% with total_qty=cart|length %}
                <div id="cart-qty" class="d-inline-flex">
                  {% if total_qty > 0 %}
                    {{ total_qty }}
                  {% else %}
                  0
                  {% endif %}              
                </div>
              {% endwith %}
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart3"
                viewBox="0 0 16 16">
                <path
                  d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
              </svg>
              Cart
            </a>
          </div>
        </div>
      </nav>
    </header>
    


    <div id="content">{% block content %}{% endblock content %}</div>


  </body>

</html>

templates/store/cart/summary.html
{% extends '../base.html' %} 
{% load static %}
{% block title %}Cart items{% endblock %} 

{% block content %}

<main class="pt-5">
<div class="container">
  <h1 class="h5">Shopping cart</h1>
  {% for item in cart %}

  {% with product=item.product %}
  <div data-index="{{product.id}}" class="row mb-4 border product-item">

    <div class="col-md-3 col-lg-2 order-md-first bg-light">
      <img class="img-fluid mx-auto d-block" width="120px" alt="Responsive image"    src="{{ product.image.url }}">
    </div>
    <div class="col-md-9 col-lg-10 ps-md-3 ps-lg-10">
      <a href="{{ product.get_absolute_url }}" class="text-decoration-none text-reset"><h1 class="h5 pt-2">{{ product.title }}</h1></a>
      <div class="border">
        <div class="col border-bottom">
          <div class="row p-3">
            <div class="col-6">Total Price</div>
            <div class="col-6 text-end"><span class="h6 fw-bold">${{ item.total_price }}</span></div>
          </div>
        </div>
        <div class="col">
          <div class="row p-3">
            <div class="col-12">
              <label for="select">Qty</label> 
              <select id="select">
                <option selected>
                  {{ item.qty }}
                </option>
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
              </select>
              <button type="button" id="update-button" data-index="{{product.id}}" class="btn btn-outline-secondary btn-sm update-button">
                Update
              </button>
              <button type="button" id="delete-button" data-index="{{product.id}}" class="btn btn-outline-secondary btn-sm delete-button" >
                Delete
              </button>
            </div>

          </div>

        </div>
      </div>
  </div>

  {% endwith %}
  {% endfor %}
  <div class="col-12 text-end">
    <div class="h6 fw-bold">Sub Total: $<span id="subtotal">{{ cart.get_total_price }}</span></div>
  </div>
  </div>
</main>

<script>
  $(document).on('click', '.delete-button', function(e){
    e.preventDefault();
    var prodid = $(this).data('index');
    $.ajax({
      type: 'POST',
      url: '{% url "cart:cart_delete" %}',
      data:{
        productid: $(this).data('index'),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: 'post'
      },
      success : function (json){
        $('.product-item[data-index="'+ prodid +'"]').remove();
      },
      error : function (xhr, errmsg, err){}
    });
  })
</script>
      
{% endblock content %}

templates/store/home.html
{% extends './base.html' %} 
{% load static %}
{% block title %}Home{% endblock %} 
 
{% block content %}

<main>

  <section class="py-5 text-center container">

    <div class="container">
    
      <div class="nav-scroller py-1 mb-3 ">
        <nav class="nav d-flex justify-content-between ">
          <a class="p-2 link-secondary" href="https://www.bbc.com/news/world" >World</a>
          <a class="p-2 link-secondary" href="https://ronbpost.com/">Nepal</a>
          <a class="p-2 link-secondary" href="https://www.technology.org/">New Technology</a>
          <a class="p-2 link-secondary" href="https://freecoursesite.com/">Free Course</a>
          <a class="p-2 link-secondary" href="https://www.linkedin.com/company/global-we-tech-cares/">Internship</a>
          <a class="p-2 link-secondary" href="https://www.youtube.com/channel/UCzhz1JecArdYlHo2zu_2B3Q">Vlogs</a>
        </nav>
      </div>
    </div>
    
    <main class="container">
      <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
        <div class="col-md-6 px-0">
          <h1 class="display-4 fst-italic">Divine World Embrace the change</h1>
          <p class="lead my-3">Technology is constantly pushing the boundaries of what is possible, enabling us to solve some of the world's most pressing problems and improve our daily lives in ways we never thought possible</p>
          <p class="lead mb-0"><a href="https://techcrunch.com/" class="text-white fw-bold">Continue reading...</a></p>
        </div>
      </div>
    
      <div class="row mb-2">
        <div class="col-md-6">
          <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative tabb-1">
            <div class="col p-4 d-flex flex-column position-static">
              <strong class="d-inline-block mb-2 text-primary">Technology</strong>
              <h3 class="mb-0">Keep Updated to Modern World</h3>
              <a href="https://www.wired.com/"><p class="mb-0">Click here</p></a>
            </div>
            <div class="col-auto d-none d-lg-block">
    
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative tabb-2">
            <div class="col p-4 d-flex flex-column position-static">
              <strong class="d-inline-block mb-2 text-success">Something New</strong>
              <h3 class="mb-0">New inventions</h3>
              <a href="https://www.digitaltrends.com/"><p class="mb-0">Click here</p></a>
            </div>
            <div class="col-auto d-none d-lg-block">
    
            </div>
          </div>
        </div>
      </div>
    
      <div class="row g-5">
        <div class="col-md-8">
          
            

            <div class="hawa">
              <h3>Tech Career</h3>
              <p>Don't get left behind be a modern man.</p>
              <table class="table">
                <thead>
                  <tr>
                    <th>Name</th>
                    <th>Duration</th>
                    <th>Price</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>Web Development</td>
                    <td>3 months</td>
                    <td>Rs.15000</td>
                  </tr>
                  <tr>
                    <td>Mobile App Development</td>
                    <td>3 Months</td>
                    <td>Rs. 15000</td>
                  </tr>
                  <tr>
                    <td>Data Structure and Algorithm</td>
                    <td>1 Month</td>
                    <td>Rs. 10000</td>
                  </tr>
                </tbody>
                <tfoot>
                  <tr>
                    <td>Fullstack Web Development</td>
                    <td>6 Months</td>
                    <td>Rs. 30000</td>
                  </tr>
                </tfoot>
              </table>
      
              <p></p>

            </div>

           
          </article>
    
          
    
        </div>
    
        <div class="col-md-4 sidexx">
          <div class="position-sticky" style="top: 2rem;">
            <div class="p-4 mb-3 bg-light rounded">
              <h4 class="fst-italic">About</h4>
              <p class="mb-0">Divine World is a company with a noble purpose of helping people by providing free goods and services to those in need.</p>
            </div>
    
    
            <div class="p-4">
              <h4 class="fst-italic">Contact</h4>
              <ol class="list-unstyled">
                <li><a href="https://github.com/DipeshPaudel1999">GitHub</a></li>
                <li><a href="https://www.youtube.com/channel/UCzhz1JecArdYlHo2zu_2B3Q">Youtube</a></li>
                <li><a href="https://www.instagram.com/er_dipesh_paudel/">Instagram</a></li>
                <li><a href="https://www.facebook.com/deepesh.paudel.7">Facebook</a></li>
              </ol>
            </div>
          </div>
        </div>
      </div>
    
    </main>

    <div class="row py-lg-3 wild-wise">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Wild, Wise & Free.</h1>
        <p class="lead text-muted">New accessories and Secret items that are extremely useful in real world. These modern world products are meant to make you more efficient, productive and give you modern and smart look.</p>
        <p>
          <a href="https://dipeshpaudel1999.github.io/Startup_Website/" class="btn btn-primary my-2">Join Our Community</a>
        </p>
      </div>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">
      <div class="pb-3 h5">All Items</div>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 g-3">

        {% for product in products %}

        <div class="col">
          <div class="card shadow-sm">
            <img class="img-fluid" src="{{ product.image.url }}" alt="Responsive image" >
            <div class="card-body">
              <p class="card-text">
                <a class="text-dark text-decoration-none" href="{{ product.get_absolute_url }}"> {{ product.title }} </a>
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">2 min read</small>
              </div>
            </div>
          </div>
        </div>

        {% endfor %}
        
      </div>
    </div>
  </div>

  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Future generation is here!</h1>
        <p class="lead text-muted">If you're Modern man with modern mindset you can change the world.</p>
        <p>
          <a href="https://dipeshpaudel1999.github.io/Startup_Website/" class="btn btn-primary my-2">Join Our Community</a>
          <a href="https://www.linkedin.com/in/dipesh-paudel-989bb7190/" class="btn btn-primary my-2">Contact Engineer Dipesh</a>
        </p>
      </div>
    </div>
  </section>
</main>
{% endblock content %}

templates/store/products/category.html
{% extends '../base.html' %} 
{% load static %}
{% block title %}Home{% endblock %} 
 
{% block content %}

<main>
  <div class="album py-5 bg-light">
    <div class="container">
      <div class="pb-3 h5">{{ category.name|title }}</div>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 g-3">

        {% for product in products %}

        <div class="col">
          <div class="card shadow-sm">
            <img class="img-fluid" src="{{ product.image.url }}" alt="Responsive image" >
            <div class="card-body">
              <p class="card-text">
                <a class="text-dark text-decoration-none" href="{{ product.get_absolute_url }}"> {{ product.title }} </a>
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">2 min read</small>
              </div>
            </div>
          </div>
        </div>

        {% endfor %}

      </div>
    </div>
  </div>


</main>
{% endblock content %}

templates/store/products/single.html
{% extends "../base.html" %}

{% block content %}
<div class="container">
  <main class="pt-5">
    <div class="row g-3">
      <div class="col-md-5 col-lg-5 order-md-first bg-light">
        <img class="img-fluid mx-auto d-block" width="200px" src="{{ product.image.url }}" alt="Responsive image">
      </div>
      <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
        <h1 class="mb-0 h4">{{ product.title }}</h1>
        <p><span class="lead">{{ product.author }}</span>(Owner)</p>
        <p>{{ product.description|slice:":355" }}...</p>
        <div class="border">
          <div class="col border-bottom">
            <div class="row p-3">
              <div class="col-6">Purchase at:</div>
              <div class="col-6 text-end"><span class="h4 fw-bold">{{product.price }}$</span></div>
            </div>
          </div>
          <div class="col">
            <div class="row p-3">
              <div class="col-6">
                <label for="select">Qty</label>
                <select name="" id="select">
                  <option value="1">1</option>
                  <option value="2">2</option>
                  <option value="3">3</option>
                  <option value="4">4</option>
                </select>
              </div>
            <div class="col-6 text-end"><button id="add-button" value=" {{ product.id }}" type="button" class="btn btn-secondary btn-sm">Add to Cart</button></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
</div>
<script>
  $(document).on('click', '#add-button', function(e){
    e.preventDefault();
    $.ajax({
      type: 'POST',
      url: '{% url "cart:cart_add" %}',
      data:{
        productid:$('#add-button').val(),
        productqty:$('#select option:selected').text(),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: 'post'
      },
      success : function (json){
        document.getElementById("cart-qty").innerHTML = json.qty
      },
      error : function (xhr, errmsg, err){}
    });
  })
</script>
{% endblock content %}